on:
  workflow_dispatch:

name: CI build

jobs:
  buildBullseye:
    name: Create Debian Bullseye ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Debian Bullseye ISO
        id: build_bullseye_iso
        run: make buildDebianBullseye
      - name: Test Debian Bullseye ISO
        id: test_bullseye_iso
        run: make testExampleBullseye
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
  buildJammy:
    name: Create Ubuntu Jammy ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu Jammy ISO
        id: build_jammy_iso
        run: make buildUbuntuJammy
      - name: Test Ubuntu Jammy ISO
        id: test_jammy_iso
        run: make testExampleJammy
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
  buildNeon:
    name: Create Kde Neon ISO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu Jammy ISO
        id: build_neon_iso
        run: make buildKdeNeon
      - name: Test Kde Neon ISO
        id: test_neon_iso
        run: make testExampleNeon
      - name: Debugging with ssh
        uses: lhotari/action-upterm@v1
